// Seed data for the Graveyard of Dead Projects prototype.
// Dead projects: publicly documented cases (research, status Sept 2026). Coordinates are approximate.
// Red zones: derived from documented grid refusals (areas are approximate / illustrative).
// Yellow zones: DEMO DATA ONLY – there is no public source for future free capacity (that is the point).

const REASONS = {
  grid:       { label: "Grid connection",            color: "#d62828" },
  economics:  { label: "Economics / auction prices", color: "#f77f00" },
  land:       { label: "Land / municipality",        color: "#7b5e3b" },
  opposition: { label: "Opposition / permitting",    color: "#6a4c93" },
  finance:    { label: "Financing / insolvency",     color: "#495057" },
};

const STATUS = {
  abandoned:  "Abandoned",
  onhold:     "On hold",
  litigation: "In litigation",
  delayed:    "Delayed",
  downsized:  "Downsized",
  insolvency: "Insolvency",
  revived:    "Revived",
};

const SEED_PROJECTS = [
  { id: "p1", name: "Solar park Limbach-Dorf", developer: "Statkraft", tech: "solar", mw: 30,
    lat: 49.43, lng: 6.83, place: "Schmelz, Saarland", country: "DE", operator: "",
    reasons: ["grid"], status: "abandoned", year: 2026,
    text: "Assigned grid connection point far away from the site; required line construction too costly.",
    quote: "Der für das Projekt uns zugewiesene Netzanschlusspunkt liegt weit vom geplanten Standort entfernt.",
    source: "https://www.statkraft.de/ueber-statkraft/standorte/limbach-dorf-solarpark/" },
  { id: "p2", name: "Solar + storage Niederlauken", developer: "Statkraft", tech: "solar", mw: 57,
    lat: 50.33, lng: 8.39, place: "Weilrod, Hesse", country: "DE", operator: "",
    reasons: ["grid", "land"], status: "abandoned", year: 2026,
    text: "Municipality capped area at 10 ha while the connection required an own substation – costs no longer covered. Connection had been reserved.",
    quote: "Wir bedauern sehr, dass wir den Solarpark Niederlauken unter diesen Rahmenbedingungen nicht weiterverfolgen können.",
    source: "https://www.solarserver.de/2026/05/08/statkraft-beendet-planung-fuer-solarpark-mit-speicher-in-nrw/" },
  { id: "p3", name: "Battery storage (110 kV) – BESS Germany 1", developer: "BESS Germany 1 GmbH", tech: "storage", mw: 100,
    lat: 52.45, lng: 13.95, place: "Brandenburg (site anonymised)", country: "DE", operator: "E.ON edis",
    reasons: ["grid"], status: "litigation", year: 2026,
    text: "Connection request refused (also at reduced capacity). BNetzA BK6-25-325 upheld refusal: capacity only after grid expansion in approx. 8–10 years.",
    quote: "Netzausbau in ca. acht bis zehn Jahren verfügbar",
    source: "https://www.pv-magazine.de/2026/05/22/bundesnetzagentur-billigt-verweigerung-von-netzanschluss-fuer-batteriespeicher/" },
  { id: "p4", name: "BASF solar park Frankenthal", developer: "BASF", tech: "solar", mw: 140,
    lat: 49.53, lng: 8.35, place: "Frankenthal, Rhineland-Palatinate", country: "DE", operator: "Pfalzwerke Netz",
    reasons: ["grid"], status: "onhold", year: 2026, weakSource: true,
    text: "Grid operator reportedly refuses 140 MW at a single connection point (overload, voltage). Construction start postponed indefinitely.",
    source: "https://blackout-news.de/aktuelles/basf-plant-mega-solarpark-verweigerter-netzanschluss-blockiert-industrieprojekt/" },
  { id: "p5", name: "Hellweg Wind – 4 wind farms Höxter", developer: "Hellweg Wind", tech: "wind", mw: 250,
    lat: 51.77, lng: 9.38, place: "Kreis Höxter, NRW", country: "DE", operator: "Avacon",
    reasons: ["grid"], status: "litigation", year: 2025,
    text: "Grid operator refuses nearest connection point; developer sues. Avacon won first instance.",
    quote: "Der Netzbetreiber sagt einfach: ‚Unsere Leitung ist voll‘, ohne transparente und nachvollziehbare Netzdaten vorzulegen.",
    source: "https://www.windindustrie-in-deutschland.de/energate/netzanschluesse-hellweg-wind-klagt-gegen-avacon-35401e" },
  { id: "p6", name: "PV Balzhausen", developer: "Vensol", tech: "solar", mw: 10,
    lat: 48.24, lng: 10.49, place: "Balzhausen, Bavarian Swabia", country: "DE", operator: "LEW Verteilnetz",
    reasons: ["grid"], status: "revived", year: 2025,
    text: "Put on ice due to grid situation – later realised via the LEW/Bayernwerk 'Einspeisesteckdose' capacity pilot. A resurrection case.",
    source: "https://www.pv-magazine.de/2025/04/07/pv-magazine-podcast-lew-wie-bekommt-man-schneller-einen-netzanschluss/" },
  { id: "p7", name: "Solar park A29 Wardenburg", developer: "Wattmanufactur", tech: "solar", mw: 20,
    lat: 53.06, lng: 8.20, place: "Wardenburg, Lower Saxony", country: "DE", operator: "EWE Netz",
    reasons: ["grid"], status: "onhold", year: 2026,
    text: "Fully planned, but no final grid connection point. Nearest substation with capacity ~10 km away (Oldenburg-Kreyenbrück), needs easements along the route.",
    quote: "Wir bedauern sehr, dass sich die Anbindung an das Stromnetz als so komplex und schwierig darstellt.",
    source: "https://www.nwzonline.de/oldenburg-kreis/erster-solarpark-in-gemeinde-wardenburg-foerderung-und-netzanschluss-bremsen-baustart-an-a29_a_4,3,197901687.html" },
  { id: "p8", name: "Solar park Henschleben (phase 2)", developer: "Naturstrom", tech: "solar", mw: 8.5,
    lat: 51.13, lng: 10.93, place: "Henschleben, Thuringia", country: "DE", operator: "Thüringer Energienetze",
    reasons: ["grid"], status: "delayed", year: 2022,
    text: "Built but could not feed in until substation Walschleben was expanded; 8 km cable route needed.",
    source: "https://www.pv-magazine.de/2022/11/02/umspannwerk-ausbau-verzoegert-netzanschluss-von-naturstrom-solarpark/" },
  { id: "p9", name: "Solar park Krempendorf", developer: "Parabel", tech: "solar", mw: 50,
    lat: 53.17, lng: 12.08, place: "Northern Brandenburg", country: "DE", operator: "",
    reasons: ["grid"], status: "delayed", year: 2024,
    text: "Grid connection the bottleneck: own cable routes of up to 30 km into the 110/380 kV grid required.",
    source: "https://www.sonnenenergie.de/index.php?id=30&no_cache=1&tx_ttnews%5Btt_news%5D=223" },
  { id: "p10", name: "Wind farm Märkerwald-Dierdorf", developer: "ABO Energy", tech: "wind", mw: 54.4,
    lat: 50.54, lng: 7.66, place: "Kreis Neuwied, Rhineland-Palatinate", country: "DE", operator: "",
    reasons: ["economics"], status: "abandoned", year: 2026,
    text: "Permit application withdrawn after May 2026 auction: 6,409 MW bids for 2,495 MW, award values down to ~5.06 ct/kWh.",
    quote: "Unter den aktuellen Bedingungen ist die Realisierung des Windparks wirtschaftlich nicht darstellbar.",
    source: "https://www.nr-kurier.de/artikel/175590-sturmflaute-im-westerwald--windpark-projekt--maerkerwald-dierdorf--scheitert-an-preisverfall" },
  { id: "p11", name: "Wind farm Renningen", developer: "ABO Energy", tech: "wind", mw: 40,
    lat: 48.77, lng: 8.93, place: "Kreis Böblingen, BW", country: "DE", operator: "",
    reasons: ["finance", "opposition"], status: "onhold", year: 2026,
    text: "Planning suspended due to ABO Energy's financial situation; parallel citizens' initiative against the project.",
    source: "https://www.renningen.de/umwelt-klimaschutz/klimaschutz/windpark/" },
  { id: "p12", name: "Wind farm Gieseler Forst", developer: "Juwi", tech: "wind", mw: 90,
    lat: 50.59, lng: 9.54, place: "Großenlüder, Hesse", country: "DE", operator: "",
    reasons: ["economics", "opposition"], status: "abandoned", year: 2025,
    text: "Lease cancelled citing oversupply of priority areas and falling auction yields. Citizens claim protected biotopes stopped it – reason disputed.",
    source: "https://www.hessenschau.de/wirtschaft/windpark-grossenlueder-vorerst-gescheitert-streit-um-die-gruende-fuer-das-aus-v1,windpark-giseler-forst-100.html" },
  { id: "p13", name: "Solar park Hutzelgärten", developer: "Juwi", tech: "solar", mw: 8,
    lat: 48.93, lng: 9.49, place: "Weissach im Tal, BW", country: "DE", operator: "",
    reasons: ["land", "economics"], status: "abandoned", year: 2025,
    text: "Contaminated sites reduced usable area – project no longer economic.",
    quote: "Diese Reduzierung macht das Projekt für die Juwi GmbH zurzeit unwirtschaftlich.",
    source: "https://www.bkz.de/nachrichten/solarpark-in-weissach-im-tal-wird-zunaechst-nicht-realisiert-181699.html?bPrint=true" },
  { id: "p14", name: "Solar park Asbachtal", developer: "RheinEnergie / AggerEnergie", tech: "solar", mw: 7.6,
    lat: 50.87, lng: 7.73, place: "Morsbach, NRW", country: "DE", operator: "",
    reasons: ["land", "opposition", "economics"], status: "abandoned", year: 2026,
    text: "Council cut area from 30 ha to 8.3 ha after resident protests – no longer economically feasible.",
    quote: "wirtschaftlich nicht mehr realisierbar",
    source: "https://www.radioberg.de/artikel/morsbach-solarpark-asbachtal-wirtschaftlich-nicht-machbar-2624252" },
  { id: "p15", name: "Wind site Zollernalb", developer: "Stadtwerke Stuttgart / Uhl Windkraft", tech: "wind", mw: 42,
    lat: 48.25, lng: 8.95, place: "Zollernalbkreis, BW", country: "DE", operator: "",
    reasons: ["economics"], status: "abandoned", year: 2025,
    text: "Wind conditions below forecast – project not economic.",
    source: "https://www.windindustrie-in-deutschland.de/energate/stadtwerke-stuttgart-geben-weiteres-windprojekt-auf-e7d347" },
  { id: "p16", name: "Enerparc PV+storage portfolio (~90 projects)", developer: "Enerparc", tech: "solar", mw: 1500,
    lat: 53.55, lng: 9.99, place: "Hamburg (HQ – projects not named)", country: "DE", operator: "",
    reasons: ["finance"], status: "insolvency", year: 2026,
    text: "Insolvency filed 07.09.2026 after financing for PV projects with batteries failed.",
    quote: "Eine relevante Finanzierung für Photovoltaik-Projekte mit Batteriespeichern ist gescheitert",
    source: "https://www.pv-magazine.de/2026/09/15/gescheiterte-finanzierung-loeste-enerparc-insolvenz-aus-investorenprozess-soll-bald-starten/" },
  { id: "p17", name: "Sowitec Group projects", developer: "Sowitec", tech: "wind", mw: 0,
    lat: 48.40, lng: 9.20, place: "Sonnenbühl, BW (HQ)", country: "DE", operator: "",
    reasons: ["finance"], status: "insolvency", year: 2026,
    text: "Insolvency of parent and three subsidiaries; individual failed projects not named.",
    source: "https://www.agrarheute.com/energie/windanlagenbauer-insolvent-billigkonkurrenz-china-mithalten-641813" },
  { id: "p18", name: "Solar park Rhein-Sieg-Kreis", developer: "MEC Energy", tech: "solar", mw: 0,
    lat: 50.78, lng: 7.30, place: "Rhein-Sieg-Kreis, NRW", country: "DE", operator: "",
    reasons: ["finance"], status: "insolvency", year: 2026,
    text: "Developer insolvent; future of the planned solar park open, public hearing cancelled.",
    source: "https://www.agrarheute.com/energie/strom/pv-pleite-solarpark-entwickler-meldet-insolvenz-zukunft-ungewiss-636477" },
  // Switzerland / Liechtenstein – alpine solar (Solarexpress)
  { id: "p19", name: "Tambo-Solar", developer: "EWZ", tech: "solar", mw: 0,
    lat: 46.55, lng: 9.32, place: "Splügen, GR", country: "CH", operator: "",
    reasons: ["opposition"], status: "abandoned", year: 2024,
    text: "Stopped due to tourism interests and local opposition – grid infrastructure was available.",
    source: "https://www.pv-magazine.de/2024/03/25/ewz-stellt-planungen-fuer-hochalpines-photovoltaik-kraftwerk-ein/" },
  { id: "p20", name: "Nandro-Solar", developer: "EWZ", tech: "solar", mw: 0,
    lat: 46.55, lng: 9.55, place: "Surses, GR", country: "CH", operator: "",
    reasons: ["opposition"], status: "abandoned", year: 2024,
    text: "Rejected by municipal assembly (Jan 2024).",
    source: "https://www.suedostschweiz.ch/graubuenden/planung-in-spluegen-eingestellt-zweites-solarprojekt-in-graubuenden-wird-gestoppt-73528" },
  { id: "p21", name: "Glarus Süd / Friiteren", developer: "Axpo", tech: "solar", mw: 10,
    lat: 46.93, lng: 9.05, place: "Glarus Süd", country: "CH", operator: "",
    reasons: ["economics", "opposition"], status: "abandoned", year: 2024,
    text: "Natural hazards, environmental compatibility and too low yield.",
    source: "https://www.axpo.com/ch/de/newsroom/medienmitteilungen/2024/Axpo-stellt-geplantes-alpines-Solarprojekt-ein.html" },
  { id: "p22", name: "Ilanz / Surselva", developer: "Axpo", tech: "solar", mw: 0,
    lat: 46.77, lng: 9.20, place: "Ilanz, GR", country: "CH", operator: "",
    reasons: ["opposition"], status: "abandoned", year: 2024,
    text: "Rejected in local referendum.",
    source: "https://www.nzz.ch/schweiz/alpine-solaranlagen-auf-die-goldgraeberstimmung-folgt-die-grosse-ernuechterung-ld.1769385" },
  { id: "p23", name: "Sufers", developer: "Alpiq", tech: "solar", mw: 0,
    lat: 46.57, lng: 9.37, place: "Sufers, GR", country: "CH", operator: "",
    reasons: ["economics"], status: "abandoned", year: 2024,
    text: "Lack of profitability and planning security.",
    source: "https://www.eenews.ch/de/biomasse/article/56706/alpiq-alpine-solaranlage-in-sufers-im-graubunden-wird-nicht-gebaut" },
  { id: "p24", name: "Tschingel", developer: "BKW", tech: "solar", mw: 0,
    lat: 46.70, lng: 8.20, place: "Schattenhalb, BE", country: "CH", operator: "",
    reasons: ["opposition", "economics"], status: "abandoned", year: 2025,
    text: "Opposition, protected areas and costs.",
    source: "https://www.bernerzeitung.ch/solarenergie-bkw-verzichtet-auf-alpine-solaranlage-tschingel-889361116852" },
  { id: "p25", name: "Vorab glacier solar", developer: "Repower / Weisse Arena", tech: "solar", mw: 0,
    lat: 46.87, lng: 9.18, place: "Laax, GR", country: "CH", operator: "",
    reasons: ["economics"], status: "onhold", year: 2026,
    text: "Shelved on 15.09.2026 despite legally binding building permit – economics.",
    quote: "Es ist nicht realistisch, günstige Anlagen zu bauen.",
    source: "https://www.suedostschweiz.ch/graubuenden/solarprojekt-von-repower-am-laaxer-vorab-verschwindet-vorlaeufig-in-der-schublade-2161484" },
  { id: "p26", name: "Sareis", developer: "LKW", tech: "solar", mw: 0,
    lat: 47.12, lng: 9.57, place: "Triesenberg", country: "LI", operator: "",
    reasons: ["economics"], status: "abandoned", year: 2024,
    text: "Abandoned because of costs.",
    source: "https://solargenossenschaft.li/news/" },
  { id: "p27", name: "Vispertal Solar", developer: "EnAlpin", tech: "solar", mw: 0,
    lat: 46.23, lng: 7.90, place: "Upper Valais", country: "CH", operator: "Swissgrid",
    reasons: ["grid", "opposition"], status: "downsized", year: 2023, weakSource: true,
    text: "Significantly downsized due to natural hazards and missing grid connection.",
    quote: "Naturgefahren und der fehlende Netzanschluss",
    source: "https://www.stromzeit.ch/blog/anlagen-8/alpine-solaranlagen-in-der-schweiz-beitrag-zur-stromsicherheit-und-zur-schliessung-der-winterlucke-mit-grunem-strom-eine-ubersicht-465" },
  { id: "p28", name: "Several project ideas Davos-Klosters", developer: "(anonymous)", tech: "solar", mw: 0,
    lat: 46.80, lng: 9.84, place: "Davos-Klosters, GR", country: "CH", operator: "",
    reasons: ["grid"], status: "abandoned", year: 2023,
    text: "Several project ideas dropped – not enough grid capacity to transport the power.",
    quote: "…weil nicht genügend Netzkapazitäten vorhanden sind, um den Strom zu transportieren.",
    source: "https://www.nzz.ch/schweiz/alpine-solaranlagen-auf-die-goldgraeberstimmung-folgt-die-grosse-ernuechterung-ld.1769385" },
];

// Red zones: grid blocked. Areas approximate.
const RED_ZONES = [
  { id: "r1", name: "E.ON edis 110 kV sub-area (Brandenburg)", lat: 52.45, lng: 13.95, radiusKm: 30,
    operator: "E.ON edis", why: "Load-side capacity bottleneck – connection of large storage refused, would impair voltage quality. Confirmed by BNetzA (BK6-25-325).",
    until: "~2034–2036 (grid expansion in approx. 8–10 years)", illustrative: true },
  { id: "r2", name: "Frankenthal / Ludwigshafen area", lat: 49.53, lng: 8.35, radiusKm: 18,
    operator: "Pfalzwerke Netz", why: "Overload and voltage issues – 140 MW at a single connection point refused.",
    until: "Unknown – no binding date communicated" },
  { id: "r3", name: "Kreis Höxter", lat: 51.77, lng: 9.38, radiusKm: 25,
    operator: "Avacon", why: "Nearest connection point refused: 'line is full'. No transparent grid data provided.",
    until: "Unknown – in litigation" },
  { id: "r4", name: "Upper Valais (Wallis)", lat: 46.25, lng: 7.85, radiusKm: 35,
    operator: "Swissgrid", why: "Large volumes cannot be transported before transmission grid expansion.",
    until: "2028 at the earliest" },
  { id: "r5", name: "Davos-Klosters", lat: 46.80, lng: 9.84, radiusKm: 15,
    operator: "", why: "Not enough grid capacity to transport the power – several project ideas dropped.",
    until: "Unknown" },
];

// Yellow zones: capacity expected to free up. DEMO DATA.
const YELLOW_ZONES = [
  { id: "y1", name: "Substation Oldenburg-Kreyenbrück", lat: 53.11, lng: 8.21, radiusKm: 12,
    operator: "EWE Netz", mw: 10, from: "2028", baseInterest: 5 },
  { id: "y2", name: "Weilrod / Hochtaunus (released reservation)", lat: 50.33, lng: 8.39, radiusKm: 12,
    operator: "", mw: 20, from: "2027", baseInterest: 3,
    note: "Connection was reserved for the abandoned Niederlauken project." },
  { id: "y3", name: "Schmelz / Saarlouis connection point", lat: 49.40, lng: 6.90, radiusKm: 12,
    operator: "", mw: 30, from: "2027", baseInterest: 2,
    note: "Connection point assigned to the abandoned Limbach-Dorf project." },
  { id: "y4", name: "Bavarian Swabia 'feed-in socket' round 2", lat: 48.30, lng: 10.55, radiusKm: 18,
    operator: "LEW Verteilnetz", mw: 15, from: "2028", baseInterest: 7 },
  { id: "y5", name: "Walschleben substation (expanded)", lat: 51.07, lng: 10.93, radiusKm: 12,
    operator: "Thüringer Energienetze", mw: 12, from: "2027", baseInterest: 1 },
];
